### PR TITLE
Add clarification for different generic footprints

### PR DESCRIPTION
**Pull request by fruchti**
Handles #12. @bsilver8192: Is this what you had in mind?

### CODE REVIEW

**Comment by bsilver8192** [comment]
Makes sense. Seems worth adding this wording.

I don't think it really addresses the hard part of the problem though. If I'm creating a new part that has a package called `TSSOP-20` in its datasheet, and there's a generic TSSOP-20, how would I realize that it doesn't actually line up with the generic package? Even worse, if I'm creating an STM part that says it's TSSOP-20, and there are no TSSOP-20 packages, how would I realize that STM's version is special and belongs in the manufacturer/stm folder? "Know everything" isn't a real answer, but I'm having trouble coming up with anything else.

**Comment by fruchti** [comment]
> If I'm creating a new part that has a package called `TSSOP-20` in its datasheet, and there's a generic TSSOP-20, how would I realize that it doesn't actually line up with the generic package?

You’ll always have to check the package when using an existing one for your new part. There’s really no way around this as checking every existing drawing to create a truly generic package isn’t feasible. A ‘list of checked manufacturers’ for generic packages could partly solve this problem, but there might still be exceptions.

> Even worse, if I'm creating an STM part that says it's TSSOP-20, and there are no TSSOP-20 packages, how would I realize that STM's version is special and belongs in the manufacturer/stm folder?

I see three ways of going around this:

1. Require a contributor to check drawings from multiple manufacturers before adding a generic package.
2. Don’t restrict generic footprints, but require later contributors to move packages which are in retrospect not generic to `manufacturer` folders, e.g. I’d move your SOD-123F package to `manufacturer/nxp` when I create another part with ostensibly the same package but notice the land patterns don’t agree.
3. Always create packages as manufacturer-specific. When creating new parts, check existing packages from other manufacturers and promote a package to generic if the drawings agree.

Neither solution is perfect, but I’m tempted to prefer the second one because you’d have to validate the footprint for every new part anyway. With the first option, the bar for a generic footprint would be raised significantly and we might end up with lots of identical copies in different `manufacturer` folders. The last option provides a way around this option, but appears to be the most complicated and brittle to me.

**Review by bsilver8192 — APPROVED** [review]

**Comment by bsilver8192** [comment]
Makes sense to me. I guess I should go and make sure to check all the generic packages I used; I was excited to not deal with that but you have a point that I was being too optimistic.

**Comment by fruchti** [comment]
I merged this for now. We can continue the discussion about the underlying issue ‘what should be considered generic’ in #16.

**Pull request merged**
